name: Lint Code with Ruff

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        run: pipx install poetry==2.0.0
      - name: Install dependencies
        run: poetry install --with lint
      - name: Ruff Check
        run: poetry run ruff check
      - name: Ruff Format
        run: poetry run ruff format --check