name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        run: pipx install poetry==2.0.0
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish