name: Publish Library to PyPI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pipx install poetry==2.0.0
      - name: Install Dependencies
        run: poetry install
      - name: Build
        run: poetry build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: release-dists
          path: dist/
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  